// Represents the raw data "intercepted" during the simulation phase
export interface SimulationData {
  targetKeyword: string;
  timestamp: string;
  interceptedQueries: string[];
  detectedIntent: string;
  simulatedNetworkLatencyMs: number;
  metadata: {
    priceSensitivity: string;
    technicalDepth: string;
    reviewImportance: number; // 0-100
  };
}

// Represents an actionable item in the strategy
export interface ActionStep {
  title: string;
  description: string;
  priority: 'High' | 'Medium' | 'Low';
  effort: 'Easy' | 'Moderate' | 'Hard';
}

// Represents a ranking factor for visualization
export interface RankingFactor {
  name: string;
  score: number; // 0-100
  description: string;
}

// The final report generated by the analysis engine
export interface StrategyReport {
  executiveSummary: string;
  rankingFactors: RankingFactor[];
  keywordClusters: {
    topic: string;
    keywords: string[];
  }[];
  actionPlan: ActionStep[];
}

export enum AppStatus {
  IDLE = 'IDLE',
  SIMULATING = 'SIMULATING',
  ANALYZING = 'ANALYZING',
  COMPLETE = 'COMPLETE',
  ERROR = 'ERROR'
}