// Represents the data extracted from a specific LLM provider
export interface ProviderInsight {
  name: 'ChatGPT' | 'Perplexity' | 'Gemini';
  status: 'connected' | 'intercepted';
  interceptedQueries: string[]; // The specific search queries this model "used"
  latency: number;
}

// Represents the raw data "intercepted" during the simulation phase
export interface SimulationData {
  targetKeyword: string;
  timestamp: string;
  providers: ProviderInsight[]; // Now an array of providers
  detectedIntent: string;
  metadata: {
    citationProbability: string; // e.g., "Hoch (85%)"
    tableInclusion: string;      // e.g., "Ja"
    brandSentiment: string;      // e.g., "Neutral"
    priceSensitivity: string;    // Kept for backward compatibility
    technicalDepth: string;      // Kept for backward compatibility
  };
}

// Represents an actionable item in the strategy
export interface ActionStep {
  title: string;
  description: string;
  priority: 'Hoch' | 'Mittel' | 'Niedrig';
  effort: 'Leicht' | 'Mittel' | 'Schwer';
}

// Represents a ranking factor for visualization
export interface RankingFactor {
  name: string;
  score: number; // 0-100
  description: string;
}

// The final report generated by the analysis engine
export interface StrategyReport {
  executiveSummary: string;
  rankingFactors: RankingFactor[];
  keywordClusters: {
    topic: string;
    keywords: string[];
  }[];
  actionPlan: ActionStep[];
}

export enum AppStatus {
  IDLE = 'IDLE',
  SIMULATING = 'SIMULATING',
  ANALYZING = 'ANALYZING',
  COMPLETE = 'COMPLETE',
  ERROR = 'ERROR'
}